### ISSUE TITLE
How

### ISSUE THREAD

**Issue by yyyhz** [rahul3613/miniF2F-lean4#1]
Your dataset is great! I wonder how do you get informal information? Can you translate formal into informal, or you just find the informal proof from original datasets like MATH?

**Comment by yyyhz** [comment]
Your dataset is great! I wonder how do you get informal information? Can you translate formal into informal, or you just find the informal proof from original datasets like MATH?

**Comment by rahul3613** [comment]
We got the informal statements from the original Github repo of the MiniF2F dataset: https://github.com/facebookresearch/miniF2F/tree/main/informal
